### ISSUE TITLE
Adding helpers for positioning

### ISSUE THREAD

**Issue by notjb** [studiometa/scss-toolkit#30]
What about having helpers for positioning ?
Draft.scss ⬇️

```scss
/*============================================================================*\
  Position helpers
\*============================================================================*/

/** @type {Boolean} Do we need classes? */
$has-classes: false !default;

/*============================================================================*\
  Relative
\*============================================================================*/

@if $has-classes {
  .relative {
    position: relative;
  }

  @include for-each-breakpoints using ($breakpoint) {
    .relative--#{$breakpoint} {
      position: relative;
    }
  }
}


/*============================================================================*\
  Absolute
\*============================================================================*/

@if $has-classes {
  .absolute {
    position: absolute;
  }

  @include for-each-breakpoints using ($breakpoint) {
    .absolute--#{$breakpoint} {
      position: absolute;
    }
  }
}

/*============================================================================*\
  Initial
\*============================================================================*/

@if $has-classes {
  .static {
    position: static;
  }

  @include for-each-breakpoints using ($breakpoint) {
    .static--#{$breakpoint} {
      position: static;
    }
  }
}

/*============================================================================*\
  Fixed
\*============================================================================*/

@if $has-classes {
  .fixed {
    position: fixed;
  }

  @include for-each-breakpoints using ($breakpoint) {
    .fixed--#{$breakpoint} {
      position: fixed;
    }
  }
}

/*============================================================================*\
  Fixed
\*============================================================================*/

@if $has-classes {
  .sticky {
    position: sticky;
  }

  @include for-each-breakpoints using ($breakpoint) {
    .sticky--#{$breakpoint} {
      position: sticky;
    }
  }
}

```
