### ISSUE TITLE
Add breakpoints in a pseudo-element on element with "data-breakpoint"

### ISSUE THREAD

**Issue by antoine4livre** [studiometa/scss-toolkit#32]
Already used on other project, it gives the possibility to get the current breakpoint in JS scripts.
```scss
[data-breakpoint] {
  &::before {
    z-index: l('limbo');
    position: absolute;
    pointer-events: none;
    opacity: 0;
  }

  @each $breakpoint in $breakpoints {
    $key: nth($breakpoint, 1);

    @media #{md($key)} {
      &::before {
        content: '#{$key}';
      }
    }
  }
}
```

**Comment by antoine4livre** [comment]
Other way with the listing of all breakpoints:
```scss
[data-breakpoint] {
  &::before {
    z-index: l('limbo');
    position: absolute;
    pointer-events: none;
    opacity: 0;
  }

  @each $breakpoint in $breakpoints {
    $key: nth($breakpoint, 1);

    @media #{md($key)} {
      &::before {
        content: '{"list": ['+map-keys($breakpoints)+'], "current": "#{$key}"}';
      }
    }
  }
}
```
To get it with:
```js
  function getBreakpoint() {
    var bp = window
      .getComputedStyle(document.querySelector('[data-breakpoint]'), '::before')
      .getPropertyValue('content')
      .replace(/\\/g, '');
    return JSON.parse(bp.substr(1, bp.length - 2));
  }
```

And this can be use for export any SCSS data in the DOM for getting them with JS. (For colors by example ?)
