### ISSUE TITLE
[v3] Add variations to the layer classes 

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/scss-toolkit#39]
### Proposal
Adding `--above` and `--under` modifiers to the layer classes.

```css
.layer-goku {
  z-index: 9000;
}

.layer-goku--above {
  z-index: 9001;
}

.layer-goku--under {
  z-index: 8999;
}
```

The idea is to have a more precise way to stack elements on one another without adding custom CSS. For example, if you have a `modal` layer, it can be very practical to be able to place elements just above/under it. For example:

```html
<div class="layer-modal">
  ...
</div>

<p class="layer-modal--above">
  I am over the modal! 💪 
</p>
```

### 👍 Pros 
- Simpler way to stack elements on one another

### 👎 Cons
- More classes
